# -*- coding: utf-8 -*-
"""KnessetMeetingsParser.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1piHjZsb4b0oU_JqXIIIwokB4u8-D21i7

**שלב א' - טעינת הספריות הדרושות לקוד**

---
"""

!sudo apt-get install catdoc
!pip install "pip<24.1"
!pip install textract==1.6.5

"""


---


**שלב ב' - העלאת הקובץ**

[קישור לאתר](https://main.knesset.gov.il/Activity/committees/Pages/AllCommitteesAgenda.aspx?Tab=1)"""

from google.colab import files
uploaded = files.upload()

"""

---


**שלב ג' - הרצת התוכנית**
"""

import re
import textract
import subprocess
import pandas as pd
from openpyxl import load_workbook
from openpyxl.styles import Alignment, Border, Side, Font, PatternFill
import os
from bs4 import BeautifulSoup
from google.colab import files


def clean_text(original_text):
    """Removes unwanted characters from the text."""
    return re.sub(r"[^a-zA-Z0-9\u0590-\u05FF\s.,!?;:()\"'-]", "", original_text)


def extract_text_from_doc(file_name):
    """Extracts text from a .doc file."""
    html_content = subprocess.check_output(["catdoc", file_name]).decode("utf-8")
    if not html_content.strip():
        raise ValueError("Warning: HTML content is empty!")
    soup = BeautifulSoup(html_content, "html.parser")
    plain_text = soup.get_text("\n") or "empty"
    return plain_text.encode('latin1', errors="ignore").decode('windows-1255')


def save_to_excel(meetings, filepath):
    """Saves meeting details to an Excel file."""
    columns = ["יום", "שעה", "וועדה", "נושא", "הערות"]
    df = pd.DataFrame(meetings, columns=columns)
    df.to_excel(filepath, index=False)


def format_excel(filepath, row_count):
    """Applies formatting to an Excel file."""
    wb = load_workbook(filepath)
    ws = wb.active

    ws.sheet_view.rightToLeft = True
    column_widths = {'A': 10.5, 'B': 6.8, 'C': 12, 'D': 85, 'E': 25}
    for col, width in column_widths.items():
        ws.column_dimensions[col].width = width

    for i in range(1, row_count + 2):
        for j in range(1, 6):
            cell = ws.cell(row=i, column=j)
            cell.alignment = Alignment(horizontal="right", vertical="center", readingOrder=2, wrap_text=True)
            cell.font = Font(name='Calibri', size=10)
            cell.border = Border(left=Side(style='thin'), right=Side(style='thin'), top=Side(style='thin'), bottom=Side(style='thin'))

            if j == 1:
                cell.fill = PatternFill(start_color="B4C6E7", end_color="B4C6E7", fill_type="solid")
            elif j == 2:
                cell.fill = PatternFill(start_color="C6E0B4", end_color="C6E0B4", fill_type="solid")

    for cell in ws[1]:  # Make header bold
        cell.font = Font(size=12, bold=True)

    ws.freeze_panes = "A2"
    ws.auto_filter.ref = "A:E"
    wb.save(filepath)
    print(f"Excel file '{filepath}' formatted successfully!")


def parse_doc_to_excel(text, output_filepath, delimiter="יום"):
    """Parses extracted text and saves it to an Excel file."""
    cleaned_text = clean_text(text)
    valid_lines = filter_valid_lines(cleaned_text)
    meetings = extract_meeting_details(valid_lines, delimiter)
    save_to_excel(meetings, output_filepath)
    format_excel(output_filepath, len(meetings))
    files.download(output_filepath)


def extract_meeting_details(text_lines, delimiter):
    """Extracts structured meeting details from text lines."""
    text_lines = text_lines[0].split("\n")
    meetings, i = [], 0

    while i < len(text_lines):
        line = text_lines[i].strip()
        if line.startswith(delimiter):
            words = line.split(" ")
            date = " ".join(words[:6])[:-2]
            time = words[-1]
            title = text_lines[i + 2]
            subject = extract_subject(text_lines, i + 4)
            meetings.append((date, time, title, subject, ""))
            i += 3
        else:
            i += 1
    return meetings


def extract_subject(text_lines, index):
    """Extracts subject from the text, handling multiple lines."""
    subject = text_lines[index]
    if subject.startswith("משנה"):
        subject = text_lines[index + 1]
    elif subject.startswith('1.'):
        k = 1
        while text_lines[index + k].startswith(str(k + 1) + '.'):
            subject += '\n' + text_lines[index + k]
            k += 1
    return subject


def filter_valid_lines(text):
    """Filters out invalid lines from the extracted text."""
    lines = text.split("\r\r")
    return [line.strip() for line in lines if re.match(r'^\s*[a-zA-Zא-ת0-9]', line)]


if __name__ == "__main__":
    base_dir = os.getcwd()
    excel_file = "Committee_schedule.xlsx"
    file_name = list(uploaded.keys())[0]
    text_content = extract_text_from_doc(file_name)
    parse_doc_to_excel(text_content, excel_file)

# # previous version:
# import re
# import textract
# import subprocess
# import pandas as pd
# from openpyxl import load_workbook
# from openpyxl.styles import Alignment, Border, Side, Font, PatternFill
# import os
# from bs4 import BeautifulSoup
# from google.colab import files


# def clean_text(original_text):
#     """get rid of unwanted characters from the text."""
#     # Keep Hebrew, English, digits, spaces, and common punctuation
#     cleaned_text = re.sub(r"[^a-zA-Z0-9\u0590-\u05FF\s.,!?;:()\"'-]", "", original_text)
#     return cleaned_text

# def extract_text_from_doc():
#     # uploaded = files.upload()
#     # Get the filename
#     file_name = list(uploaded.keys())[0]
#     print(f"Uploaded file: {file_name}\n")
#     html_content = subprocess.check_output(["catdoc", file_name]).decode("utf-8")
#     soup = BeautifulSoup(html_content, "html.parser")
#     if html_content is None or html_content.strip() == "":
#       print("Warning: HTML content is empty or None!")
#     else:
#       plain_text = soup.get_text("\n") or "empty"  # Ensures it never returns None
#       fixed_text = plain_text.encode('latin1', errors="ignore").decode('windows-1255')  # or 'iso-8859-8'
#     return fixed_text


# def save_to_excel(meetings, excel_filepath):
#     """Saves the meeting details to an Excel file."""
#     columns = ["יום", "שעה", "וועדה", "נושא", "הערות"]  # Define column headers (matching your Excel file)
#     df = pd.DataFrame(meetings, columns=columns)  # Create a DataFrame
#     df.to_excel(excel_filepath, index=False)  # Save to Excel file


# def format_excel(excel_filepath, row):
#     col = 5
#     wb = load_workbook(excel_filepath)
#     ws = wb.active

#     ws.sheet_view.rightToLeft = True

#     ws.column_dimensions['A'].width = 8.42
#     ws.column_dimensions['B'].width = 7
#     ws.column_dimensions['C'].width = 12
#     ws.column_dimensions['D'].width = 85
#     ws.column_dimensions['E'].width = 25

#     for i in range(1, row + 2):
#         for j in range(1, col + 1):
#             if j == 1:
#                 ws.cell(row=i, column=j).fill = PatternFill(start_color="B4C6E7", end_color="B4C6E7", fill_type="solid")
#             elif j == 2:
#                 ws.cell(row=i, column=j).fill = PatternFill(start_color="C6E0B4", end_color="C6E0B4", fill_type="solid")
#             ws.cell(row=i, column=j).alignment = Alignment(horizontal="right", vertical="center", readingOrder=2, wrap_text=True)
#             ws.cell(row=i, column=j).font = Font(name='Calibri', size=10)  # Set font
#             ws.cell(row=i, column=j).border = Border(left=Side(style='thin'),
#                                                      right=Side(style='thin'),
#                                                      top=Side(style='thin'),
#                                                      bottom=Side(style='thin'))

#             # make header bold
#             for cell in ws[1]:
#                 cell.font = Font(size=12, bold=True)

#     # מוסיף AutoFilter לעמודות A-E
#     ws.auto_filter.ref = "A:E"

#     wb.save(excel_filepath)
#     print(f"Excel file '{excel_filepath}' formatted successfully!")


# def parse_doc_to_excel(txt, output_excel_filepath, delimiter="יום"):
#     """
#     Parses the text  and saves the data to an Excel file.
#        :param delimiter: the character separating data fields.
#        :param output_excel_filepath: the path to save the Excel file.
#        :param txt: the text extracted from the .doc file.
#     """
#     cleand_text = clean_text(txt)
#     valid_lines = filter_valid_lines(cleand_text)
#     meetings = extract_meeting_details(valid_lines, delimiter)
#     save_to_excel(meetings, output_excel_filepath)
#     format_excel(output_excel_filepath, len(meetings))
#     files.download(output_excel_filepath)


# def extract_meeting_details(text_lines, delimiter):
#     # Split the text into individual meetings
#     text_lines = text_lines[0].split("\n")
#     print(text_lines[14][0], '\n\n')
#     meetings = []
#     i = 0
#     print(f"Number of lines: {len(text_lines)}")
#     print(f"type of text_lines: {type(text_lines)}")
#     while i < len(text_lines):
#         line = text_lines[i].strip()
#         if line.startswith(delimiter):
#             words = line.split(" ")
#             date = " ".join(words[:6])[:-2]
#             time = words[-1]
#             title = text_lines[i + 2]  # the next line is the title
#             subject = text_lines[i + 4]
#             if text_lines[i + 4].startswith("משנה"):
#               subject = text_lines[i + 5]
#             elif text_lines[i + 4].startswith('1.'):
#               k = 1
#               while text_lines[i + 4 + k].startswith(str(k+1) + '.'):
#                 subject += '\n' + text_lines[i + 4 + k]
#                 k += 1
#             # while not text_lines[i].startswith(delimiter):
#             #     subject += text_lines[i]
#             i += 3
#             meetings.append((date, time, title, subject, ""))
#         else:
#             i += 1
#     print(meetings)
#     return meetings


# def filter_valid_lines(text_):
#     lines = text_.split("\r\r")  # Split into lines
#     valid_lines = [line.strip() for line in lines if re.match(r'^\s*[a-zA-Zא-ת0-9]', line)]
#     return valid_lines  # Join back into a cleaned text


# base_dir = os.getcwd()  # Gets the current working directory
# # doc_file = os.path.join(base_dir, "Committee.doc")  # Full path to the .doc file
# excel_file = "Committee_schedule.xlsx"

# text_content = extract_text_from_doc()
# parse_doc_to_excel(text_content, excel_file)